TEST_DATA = {
    'agency': {
        'agency_cd': 'CADWR',
        'agency_med': 'CA Dept. of Water Resources',
        'agency_nm': 'California Department of Water Resources'
    },
    'alt_acy': '',
    'alt_method': '',
    'alt_va': None,
    'altitude_datum': None,
    'altitude_units': None,
    'aqfr_type': 'CONFINED',
    'country': {'country_cd': 'US', 'country_nm': 'United States of America'},
    'county': {'county_cd': '001', 'county_nm': 'Alameda County'},
    'dec_lat_va': '45.22000000',
    'dec_long_va': '34.48900000',
    'display_flag': False,
    'horizontal_datum': 'WGS66',
    'horz_acy': '17',
    'horz_method': '',
    'id': 4,
    'insert_date': '2020-09-10T20:40:03.504235Z',
    'link': '',
    'local_aquifer_name': '',
    'nat_aqfr': {'nat_aqfr_cd': 'S100CSLLWD', 'nat_aqfr_desc': 'Coastal lowlands aquifer system'},
    'insert_user': 'mickey.ca.gov',
    'update_user': 'minnie.ca.gov',
    'qw_baseline_flag': False,
    'qw_network_name': '',
    'qw_sn_flag': False,
    'qw_well_chars': '',
    'qw_well_purpose': '',
    'qw_well_purpose_notes': '',
    'qw_well_type': '',
    'site_name': 'Charmander',
    'site_no': 'CA-192902',
    'site_type': '',
    'state': {'state_cd': '06', 'state_nm': 'California'},
    'update_date': '2020-09-10T20:42:31.844812Z',
    'well_depth': None,
    'well_depth_units': None,
    'wl_baseline_flag': False,
    'wl_network_name': '',
    'wl_sn_flag': False,
    'wl_well_chars': '',
    'wl_well_purpose': '',
    'wl_well_purpose_notes': '',
    'wl_well_type': ''
}